apiVersion: 1

datasources:
  # Prometheus (local Docker)
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
    uid: prometheus
    jsonData:
      httpMethod: POST
      timeInterval: 15s
      queryTimeout: 60s

  # Loki (local Docker)
  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    editable: true
    uid: loki
    jsonData:
      maxLines: 1000
